---
title: "R scripts (and a little Python)"
description: |
  Some additional details about the website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

This page contains all of the code needed to reproduce just about every example and figure in the book. If any of the code in these scripts does not work, please let me know. For example, if a code snippet requires reading in an intermediate result I probably saved as part of a longer running chunk of code, then post an issue and I will add the missing code to reproduce it.

#### Download R code by chapter

-   [Chapter 1: Introduction](scripts/chap-intro.R)

-   [Chapter 2: Binary recursive partitioning with CART](scripts/chap-intro.R)

-   [Chapter 3: Conditional inference trees](scripts/chap-urpart.R)

-   [Chapter 4: The hitchhiker's GUIDE to modern decision trees](scripts/chap-guide.R)

-   [Chapter 5: Ensemble algorithms](scripts/chap-ensembles.R)

-   [Chapter 6: Peeking inside the "black box": post-hoc interpretability](scripts/chap-interpret.R)

-   [Chapter 7: Random forests](scripts/chap-rf.R)

-   [Chapter 8: Gradient boosting machines](scripts/chap-gbm.R)
